[package]
name = "Chet3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "chet3_bin"
path = "src/main.rs"

[lib] 
name = "chetnet1"
path = "src/chetnet1/chetnet1.rs"